In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib as mpl
import requests
from matplotlib import pyplot as plt
np.seterr(divide = 'ignore') 


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
df = pd.read_excel('Final comparison 2.xlsx')

In [3]:
df.head(10)

Unnamed: 0 PartControlNumber                    Part Description  \
0        2614     BK31V200K23GJ  PANEL-BODY SIDE RR, LH               
1        2567     KK31V200K22HA  BRA BDY SD LWR RR                    
2        2516       FK312C405AB  UNT ASY M/FUNC IVD CONTR             
3        2443       BK315E211ED  CONV & PIP ASY EXH                   
4        2828       BK315H250AE  FLTR ASY ENG CTLST EXH PRTCLT        
5         871       BK315H270DB  CONV & PRTCLT FLTR ASY EXH           
6        4897       JK315L243AB  CONV & SEL CTLST REDUC FLTR ASY      
7        3074      KK2112A650FA  PROCS ASY ENG ELETR CONTR            
8        4895        KK3R7003BB  TRANS ASY                            
9        4899     KK3T14401AAFD  WIR ASY MN                           

   Actual Price(Supplier Curr) Currency Code  \
0                     49.82929           EUR   
1                     49.82929           EUR   
2                     78.32340           EUR   
3                    201.61148           EUR   
4                    308.93787           EUR   
5                    356.31958           EUR   
6                    392.62523           EUR   
7                     82.05150           EUR   
8                    672.09110           EUR   
9                    302.12134           EUR   

                                   CSS  \
0                 Upper Body Structure   
1                 Upper Body Structure   
2                               Brakes   
3                  Exhaust (Powerpack)   
4                  Exhaust (Powerpack)   
5                  Exhaust (Powerpack)   
6                  Exhaust (Powerpack)   
7  Powertrain Controls and Calibration   
8                  Manual Transmission   
9                                  EDS   

                                CPSCII Name  Global- PMT Common value  \
0                                 Body Side            1          Yes   
1                                 Body Side            1          Yes   
2                            Brake Controls            3          Yes   
3               Emission Control Components            4          Yes   
4               Emission Control Components            4          Yes   
5               Emission Control Components            4          Yes   
6               Emission Control Components            4          Yes   
7  Powertrain and Auxiliary Control Modules            4          Yes   
8      Module - Manual or Auto Manual Trans            4          Yes   
9                  Instrument Panel Harness            5          Yes   

      Price  Price P EUR       Coef Unnamed: 12  
0  11299.99    644.09943  12.926121         NaN  
1  11299.99    644.09943  12.926121         NaN  
2  11299.99    644.09943   8.223589         NaN  
3  11299.99    644.09943   3.194756         NaN  
4  11299.99    644.09943   2.084883         NaN  
5  11299.99    644.09943   1.807645         NaN  
6  11299.99    644.09943   1.640494         NaN  
7  11299.99    644.09943   7.849941         NaN  
8  11299.99    644.09943   0.958351         NaN  
9  11299.99    644.09943   2.131923         NaN

In [4]:
del df['Unnamed: 0']

In [5]:
df.rename(columns={'Actual Price(Supplier Curr)':'actual_price'}, inplace=True)


In [6]:
df.rename(columns={'Price P EUR':'online_price'}, inplace=True)


In [7]:
df.head()

PartControlNumber                    Part Description  actual_price  \
0     BK31V200K23GJ  PANEL-BODY SIDE RR, LH                  49.82929   
1     KK31V200K22HA  BRA BDY SD LWR RR                       49.82929   
2       FK312C405AB  UNT ASY M/FUNC IVD CONTR                78.32340   
3       BK315E211ED  CONV & PIP ASY EXH                     201.61148   
4       BK315H250AE  FLTR ASY ENG CTLST EXH PRTCLT          308.93787   

  Currency Code                   CSS                  CPSCII Name  \
0           EUR  Upper Body Structure                    Body Side   
1           EUR  Upper Body Structure                    Body Side   
2           EUR                Brakes               Brake Controls   
3           EUR   Exhaust (Powerpack)  Emission Control Components   
4           EUR   Exhaust (Powerpack)  Emission Control Components   

   Global- PMT Common value     Price  online_price       Coef Unnamed: 12  
0            1          Yes  11299.99     644.09943  12.926121         NaN  
1            1          Yes  11299.99     644.09943  12.926121         NaN  
2            3          Yes  11299.99     644.09943   8.223589         NaN  
3            4          Yes  11299.99     644.09943   3.194756         NaN  
4            4          Yes  11299.99     644.09943   2.084883         NaN

In [8]:
df =  df[['actual_price', 'CPSCII Name', 'online_price']]

In [9]:
df.actual_price = np.log(df.actual_price)

In [10]:
#pd.set_option('display.max_rows', df.shape[0]+1)


In [11]:
df.replace([np.inf, -np.inf], 0, inplace=True)


In [12]:
df

actual_price                                   CPSCII Name  online_price
0         3.908603                                     Body Side     644.09943
1         3.908603                                     Body Side     644.09943
2         4.360846                                Brake Controls     644.09943
3         5.306342                   Emission Control Components     644.09943
4         5.733140                   Emission Control Components     644.09943
...            ...                                           ...           ...
1336     -2.563950                  Road Wheel and Tire Assembly       0.00000
1337      0.000000                  Road Wheel and Tire Assembly       0.00000
1338     -2.365525                        Front Rotor and Shield       0.00000
1339      1.560634  Hose Set - Coolant (includes Expansion Tank)       0.00000
1340     -2.419119      Powertrain and Auxiliary Control Modules       0.00000

[1341 rows x 3 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1, shuffle=True)

In [15]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1, shuffle=True)

In [16]:
df_train.shape

(804, 3)

In [17]:
y_train = df_train['actual_price']
y_test = df_test['actual_price']
y_val = df_val['actual_price']


In [18]:
del df_train['actual_price']
del df_test['actual_price']
del df_val['actual_price']

In [19]:
df_train['online_price']

15     525.77370
704     14.16963
208     96.43545
983      4.14390
603     20.31423
         ...    
566     22.59765
944      5.00004
109    170.95554
699     14.40276
508     26.54148
Name: online_price, Length: 804, dtype: float64

In [20]:
y_train

15     4.138582
704   -0.214184
208    2.160765
983   -0.730019
603    1.541033
         ...   
566    0.815144
944    0.078386
109    3.315289
699    0.921049
508    0.397278
Name: actual_price, Length: 804, dtype: float64

# Linear Regression Model

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
lin_reg = LinearRegression().fit(df_train[['online_price']], y_train)


In [24]:
lin_reg.score(df_train[['online_price']], y_train)

0.3601730769719984

In [25]:
y_test_pred = lin_reg.predict(df_test[['online_price']])

In [26]:
lin_reg_rmse = mean_squared_error(y_test, y_test_pred)

In [27]:
lin_reg_rmse

2.3281692926045987

# Dict Vectorizer

In [28]:
from sklearn.feature_extraction import DictVectorizer


In [29]:
dv = DictVectorizer(sparse=False)


In [30]:
train_dict = df_train.to_dict(orient='records')
val_dict = df_val.to_dict(orient='records')
test_dict = df_test.to_dict(orient='records')

In [31]:
dv.fit(train_dict)
dv.fit(val_dict)
dv.fit(test_dict)

DictVectorizer(sparse=False)

In [32]:
X_train = dv.transform(train_dict)
X_val = dv.transform(val_dict)
X_test = dv.transform(test_dict)

In [33]:
X_train.shape

(804, 112)

In [34]:
feature_names=dv.get_feature_names_out()

In [35]:
feature_names

array(['CPSCII Name=Acoustic Control Components',
       'CPSCII Name=Air Cleaner',
       'CPSCII Name=Air Handling/Body Ventilation Subsystem',
       'CPSCII Name=Applied Parts - (IP)',
       'CPSCII Name=Auxiliary Water Pump', 'CPSCII Name=Badging',
       'CPSCII Name=Battery Cables',
       'CPSCII Name=Beam Rear Axle Assembly',
       'CPSCII Name=Body And Rear End Wiring',
       'CPSCII Name=Body Dash and Cowl', 'CPSCII Name=Body Side',
       'CPSCII Name=Brake Controls', 'CPSCII Name=Brake Lines and Hoses',
       'CPSCII Name=CHMSL (Center High Mount Stop Light)',
       'CPSCII Name=Cab Back & Ring Frame',
       'CPSCII Name=Clutch Actuation Assembly',
       'CPSCII Name=Cross-Car Beam (IP)',
       'CPSCII Name=Drive Belts/Pulleys and Component Mounting Bracketry',
       'CPSCII Name=EDS Components & Fasteners',
       'CPSCII Name=Emission Control Components',
       'CPSCII Name=Emissions Additive Storage, Supply and Conditioning',
       'CPSCII Name=Engine Bay Fus

In [36]:
len(feature_names)

112

# Decision Tree

In [37]:
from sklearn.tree import DecisionTreeRegressor


In [38]:
for depth in range(1,10):
    dt = DecisionTreeRegressor(max_depth=depth)
    dt.fit(X_train, y_train)
    y_val_pred = dt.predict(X_val)
    rmse_dt = mean_squared_error(y_val_pred, y_val)
    print(depth, rmse_dt.round(2))

1 1.84
2 1.22
3 1.01
4 0.82
5 0.95
6 0.92
7 0.89
8 0.87
9 0.89


In [75]:
dt = DecisionTreeRegressor(max_depth=8)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=8)

In [76]:
y_val_pred = dt.predict(X_val)

In [77]:
rmse_dt = mean_squared_error(y_val_pred, y_val)

In [78]:
rmse_dt

0.8735987395407103

rmse 
293.9700548580357

# Random Forest


In [43]:
from sklearn.ensemble import RandomForestRegressor

In [44]:
rf = RandomForestRegressor(n_estimators=10, random_state=1, n_jobs=-1)

In [45]:
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [46]:
y_val_pred = rf.predict(X_val)

In [47]:
rmse_rf = mean_squared_error(y_val_pred, y_val)

In [74]:
rmse_rf

0.8996966778384925

In [49]:
scores = []

for n in range(10, 201, 10):
    rf = RandomForestRegressor(n_estimators=n, random_state=1)
    rf.fit(X_train, y_train)

    y_val_pred = rf.predict(X_val)
    rmse = mean_squared_error(y_val, y_val_pred)
    
    scores.append((n, rmse))

In [50]:
scores

[(10, 0.8996966778384926),
 (20, 0.8696626892633991),
 (30, 0.8625234525801624),
 (40, 0.8682918401801133),
 (50, 0.8653241330180723),
 (60, 0.8622626042740358),
 (70, 0.8690144988108018),
 (80, 0.8650750718779596),
 (90, 0.8623062573073847),
 (100, 0.8665733256851366),
 (110, 0.8626505841441761),
 (120, 0.8631444188506232),
 (130, 0.8662992221799021),
 (140, 0.8661361402595336),
 (150, 0.8704927984297909),
 (160, 0.8716513379061938),
 (170, 0.8741393151572993),
 (180, 0.8757535989638678),
 (190, 0.8755603135777567),
 (200, 0.8780511878923212)]

# XGBoost

In [51]:
import xgboost as xg


C:\Users\MI\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [52]:
xgb_r = xg.XGBRegressor(objective ='reg:linear',
                  n_estimators = 10, seed = 123)

In [53]:
xgb_r.fit(X_train, y_train)


[20:52:55] WARNING: c:\windows\temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\objective\regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=10, n_jobs=8,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=123, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=123, subsample=1, tree_method='exact', validate_parameters=1,
             verbosity=None)

In [54]:
y_test_pred = xgb_r.predict(X_test)

In [69]:
rmse_xg_test = mean_squared_error(y_test_pred, y_test)

In [70]:
rmse_xg_test

0.7461300604677716

In [71]:
y_val_pred = xgb_r.predict(X_val)


In [72]:
rmse_xg = mean_squared_error(y_val_pred, y_val)

In [73]:
rmse_xg

0.8379907517310754

In [58]:
y_val_pred_exp = np.exp(y_val_pred)

In [59]:
X_sample = X_train[20]

In [104]:
X_sample

array([[ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  1.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     , 

In [105]:
X_sample = X_sample.reshape(1,-1)

In [106]:
X_sample

array([[ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  1.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ,  0.     ,  0.     , 

In [82]:
y_sample = y_train[20]

In [83]:
y_sample

3.398166125376763

In [84]:
np.exp(y_sample)

29.909200000000002

In [85]:
sample_pred = xgb_r.predict(X_sample)


In [86]:
sample_pred

array([1.5608474], dtype=float32)

In [87]:
np.exp(sample_pred)

array([4.7628555], dtype=float32)

In [92]:
import pickle

In [94]:
pickle_out = open('xgb_r.pkl','wb')
pickle.dump(xgb_r, pickle_out)
pickle_out.close()